const express = require('express');
const cors = require('cors');
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

// Global task state for background scraping
let activeTask = {
  status: 'idle', // 'idle' | 'running' | 'completed' | 'failed'
  leads: [],
  logs: '',
  error: null
};

// Helper to parse CSV lines with quoted commas
const parseCSVLine = (line) => {
  const result = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === ',' && !inQuotes) {
      result.push(current);
      current = '';
    } else {
      current += char;
    }
  }
  result.push(current);
  return result.map(s => s.trim().replace(/^"|"$/g, ''));
};

// Start scraper in background
app.get('/api/scrape', (req, res) => {
  const query = req.query.query || 'construction';
  const location = req.query.location || 'chennai';
  const limit = req.query.limit || '10';

  if (activeTask.status === 'running') {
    return res.status(409).json({ 
      success: false, 
      message: 'Scraper is already running. Please wait for the current run to finish.' 
    });
  }

  // Reset active task status
  activeTask = {
    status: 'running',
    leads: [],
    logs: '',
    error: null
  };

  const pythonCmd = process.platform === 'win32' ? 'python' : 'python3';
  activeTask.logs += `[Server] Starting background job: ${pythonCmd} scraper.py "${query}" "${location}" ${limit}\n`;
  console.log(`[Server] Starting background job: ${pythonCmd} scraper.py "${query}" "${location}" ${limit}`);

  const pythonProcess = spawn(pythonCmd, ['scraper.py', query, location, limit]);

  let stdoutData = '';
  let stderrData = '';

  pythonProcess.stdout.on('data', (data) => {
    const chunk = data.toString();
    stdoutData += chunk;
    activeTask.logs += chunk;
  });

  pythonProcess.stderr.on('data', (data) => {
    const chunk = data.toString();
    stderrData += chunk;
    activeTask.logs += chunk;
  });

  pythonProcess.on('close', (code) => {
    console.log(`[Server] Process exited with code ${code}`);
    activeTask.logs += `[Server] Process exited with code ${code}\n`;

    if (code !== 0) {
      console.error(`[Server Error] Scraper stderr:\n${stderrData}`);
      activeTask.status = 'failed';
      activeTask.error = `Scraper exited with code ${code}`;
      return;
    }

    try {
      const csvPath = path.resolve(__dirname, 'leads.csv');
      if (!fs.existsSync(csvPath)) {
        activeTask.status = 'failed';
        activeTask.error = 'leads.csv was not generated by the scraper';
        return;
      }

      const csvData = fs.readFileSync(csvPath, 'utf8');
      const lines = csvData.split('\n').map(l => l.trim()).filter(l => l.length > 0);
      
      if (lines.length === 0) {
        activeTask.leads = [];
        activeTask.status = 'completed';
        return;
      }

      const headers = parseCSVLine(lines[0]);
      const results = [];

      for (let i = 1; i < lines.length; i++) {
        const values = parseCSVLine(lines[i]);
        const entry = {};
        headers.forEach((header, index) => {
          entry[header] = values[index] ? values[index] : 'N/A';
        });
        results.push(entry);
      }

      activeTask.leads = results;
      activeTask.status = 'completed';
      console.log(`[Server] Scraping completed. Parsed ${results.length} leads.`);
    } catch (err) {
      console.error(`[Server Error] Failed to parse leads.csv: ${err.message}`);
      activeTask.status = 'failed';
      activeTask.error = `Parse error: ${err.message}`;
    }
  });

  // Respond instantly to prevent 30s timeout
  return res.json({ 
    success: true, 
    status: 'running', 
    message: 'Scraper task successfully spawned in the background' 
  });
});

// Check task status
app.get('/api/scrape/status', (req, res) => {
  return res.json({
    success: true,
    status: activeTask.status,
    leads: activeTask.leads,
    logs: activeTask.logs,
    error: activeTask.error
  });
});

app.listen(PORT, () => {
  console.log(`Scraper backend listening on port ${PORT}`);
});
